---
products:
  - source: hktvmall
    id: H0888001_S_10012511
    name: 西班牙咸豬手
    unit: pack
    unit-convertsion: price
  - source: hktvmall
    id: H0888001_S_10139004
    name: 奧運2020 竹碗
    unit: item
    unit-convertsion: price
  - source: hktvmall
    id: H0888001_S_10138948
    name: 雞蛋
    unit: 100ml
    unit-convertsion: price / 280 * 100
    groups: group1, group2
  - source: hktvmall
    id: H0888001_S_10140667
    name: 威露士 泡沫殺菌潔手液敏感呵護
    unit: 100ml
    unit-convertsion: price / 280 * 100
    groups: group1, group2
  - source: hktvmall
    id: H0888001_S_10050052D
    name: 皇冠 三層棉柔舒適衛生紙10卷裝
    unit: roll
    unit-convertsion: price / 15
    groups: group1
  - source: hktvmall
    id: H0888001_S_10020081
    name: 白蘭氏 無糖燕窩
    unit: 100g
    unit-convertsion: price / 6 / 70 * 100
  - source: hktvmall
    id: H0888001_S_10030825
    name: Oral B - 牙齒及牙肉護理不含酒精漱口水 - 孖裝
    unit: 100ml
    unit-convertsion: price / 750 / 2 * 100
  - source: hktvmall
    id: H0888001_S_10030319
    name: Oral B - 不含酒精漱口水(孖裝)
    unit: 100ml
    unit-convertsion: price / 500 / 2 * 100
  - source: hktvmall
    id: H0888001_S_P10014683
    name: 金象牌 - 頂上茉莉香米 15公斤
    unit: kg
    unit-convertsion: price / 15
  - source: hktvmall
    id: H0888001_S_10016911A
    name: 金象牌 - 頂上茉莉香米 8公斤 x2
    unit: kg
    unit-convertsion: price / 8 / 2
  - source: hktvmall
    id: H0888001_S_10016911
    name: 金象牌 - 頂上茉莉香米 8公斤
    unit: kg
    unit-convertsion: price / 8
  - source: hktvmall
    id: H0888001_S_10015152
    name: 金象牌 - 頂上茉莉香米 5公斤
    unit: kg
    unit-convertsion: price / 5
  - source: hktvmall
    id: H0888001_S_10001735
    name: 金象牌 - 頂上茉莉香米 2公斤
    unit: kg
    unit-convertsion: price / 2
  - source: hktvmall
    id: H0888001_S_10015024C
    name: 鈣思寶 - 高鈣原味豆奶 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 4 * 250
  - source: hktvmall
    id: H0888001_S_10138408C
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 4 * 250
  - source: hktvmall
    id: H0888001_S_10138408A
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 250毫升6包裝 x 2排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
  - source: hktvmall
    id: H0888001_S_10003309
    name: 鈣思寶 - 鈣思寶高鈣原味豆奶 250毫升9包裝
    unit: 250ml
    unit-convertsion: price / 250 / 9 * 250
  - source: hktvmall
    id: H0888001_S_10003312E
    name: 鈣思寶 - 高鈣大豆健康飲品 1公升 x 6包
    unit: 250ml
    unit-convertsion: price / 1000 / 6 * 250
  - source: hktvmall
    id: H0888001_S_10130495E
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 1公升 x 6包
    unit: 250ml
    unit-convertsion: price / 1000 / 6 * 250
  - source: hktvmall
    id: H0888001_S_10130495K
    name: 鈣思寶 - 無糖大豆高鈣健康飲品 1公升 x 12包
    unit: 250ml
    unit-convertsion: price / 1000 / 12 * 250
  - source: hktvmall
    id: H0888001_S_10003312A
    name: 鈣思寶 - 高鈣大豆健康飲品 - 原味 1公升 x 3包
    unit: 250ml
    unit-convertsion: price / 1000 / 3 * 250
  - source: hktvmall
    id: H0888001_S_10130495B
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 1公升 x 3包
    unit: 250ml
    unit-convertsion: price / 1000 / 3 * 250
  - source: hktvmall
    id: S2090001_S_4001031
    name: 鈣思寶 - 高鈣原味豆奶 (250毫升 X 6 X 2)
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
  - source: hktvmall
    id: H0888001_S_10015024A
    name: 鈣思寶 - 鈣思寶高鈣原味豆奶 250毫升6包裝 x 2排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
  - source: hktvmall
    id: H8032001_S_MI-00034
    name: 鈣思寶 - 鈣思寶大豆營鈣 Calci Plus CA+ SOYA CALCIUM (BONE) N 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 24 * 250
  - source: hktvmall
    id: H8032001_S_MI-00035
    name: 鈣思寶 - 鈣思寶大豆營鈣 Calci Plus CA+ SOYA CALCIUM (BONE) N 250毫升6包裝
    unit: 250ml
    unit-convertsion: price / 250 / 6 * 250
  - source: hktvmall
    id: H7509001_S_vtm2500601
    name: 維他奶 - 維他 鈣思寶 - 綠色 原味 250ml x 6 包
    unit: 250ml
    unit-convertsion: price / 250 / 6 * 250
  - source: hktvmall
    id: H7949001_S_DRKTNMILK004
    name: 維他 - 鈣思寶 - 高鈣大豆健康飲品 (原味) 1公升
    unit: 250ml
    unit-convertsion: price / 1000 * 250
  - source: hktvmall
    id: H7949001_S_DRKTNMILK003
    name: 維他 - 鈣思寶 - 無糖大豆高鈣健康飲品 1公升
    unit: 250ml
    unit-convertsion: price / 1000 * 250
  

groups:
  - id: group1
    name: group 1
    description: description 1
  - id: group2
    name: group 2
    description: description 2

notification:
  - name: telegram 
    recipient: {{TELEGRAM_RECIPIENT}}
    condition: true

app:
  timePeriod: 30