---
products:
  - source: hktvmall
    id: H0888001_S_10050052D
    name: 皇冠 - [5條優惠裝]三層棉柔舒適衛生紙10卷裝
    unit: roll
    unit-convertsion: price / 10 / 5
    tags: 
      - 廁紙
  - source: hktvmall
    id: H0888001_S_10050052B
    name: 皇冠 - [3條優惠裝] 三層棉柔舒適衛生紙
    unit: roll
    unit-convertsion: price / 10 / 3
    tags: 
      - 廁紙
  - source: hktvmall
    id: H0888001_S_10050053D
    name: 皇冠 - [5條優惠裝]三層純白潔淨衛生紙10卷裝
    unit: roll
    unit-convertsion: price / 10 / 5
    tags: 
      - 廁紙
  - source: hktvmall
    id: H0888001_S_P10050052
    name: 皇冠 - [原箱27卷]皇冠3層棉柔舒適衛生紙
    unit: roll
    unit-convertsion: price / 27
    tags: 
      - 廁紙
  - source: hktvmall
    id: H0888001_S_P10050052A
    name: 皇冠 - [2件優惠裝] [原箱27卷]皇冠3層棉柔舒適衛生紙
    unit: roll
    unit-convertsion: price / 27 / 2
    tags: 
      - 廁紙
  - source: hktvmall
    id: H0888001_S_10050053B
    name: 皇冠 - [3條優惠裝] 三層純白衛生紙
    unit: roll
    unit-convertsion: price / 10 / 3
    tags: 
      - 廁紙
