---
products:
  - source: hktvmall
    id: H0888001_S_10015024C
    name: 鈣思寶 - 高鈣原味豆奶 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 4 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10138408C
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 4 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10138408A
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 250毫升6包裝 x 2排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10003309
    name: 鈣思寶 - 鈣思寶高鈣原味豆奶 250毫升9包裝
    unit: 250ml
    unit-convertsion: price / 250 / 9 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10003312E
    name: 鈣思寶 - 高鈣大豆健康飲品 1公升 x 6包
    unit: 250ml
    unit-convertsion: price / 1000 / 6 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10130495E
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 1公升 x 6包
    unit: 250ml
    unit-convertsion: price / 1000 / 6 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10130495K
    name: 鈣思寶 - 無糖大豆高鈣健康飲品 1公升 x 12包
    unit: 250ml
    unit-convertsion: price / 1000 / 12 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10003312A
    name: 鈣思寶 - 高鈣大豆健康飲品 - 原味 1公升 x 3包
    unit: 250ml
    unit-convertsion: price / 1000 / 3 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10130495B
    name: 鈣思寶 - 鈣思寶高鈣無糖原味豆奶 1公升 x 3包
    unit: 250ml
    unit-convertsion: price / 1000 / 3 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: S2090001_S_4001031
    name: 鈣思寶 - 高鈣原味豆奶 (250毫升 X 6 X 2)
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H0888001_S_10015024A
    name: 鈣思寶 - 鈣思寶高鈣原味豆奶 250毫升6包裝 x 2排
    unit: 250ml
    unit-convertsion: price / 250 / 6 / 2 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H8032001_S_MI-00034
    name: 鈣思寶 - 鈣思寶大豆營鈣 Calci Plus CA+ SOYA CALCIUM (BONE) N 250毫升6包裝 x 4排
    unit: 250ml
    unit-convertsion: price / 250 / 24 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H8032001_S_MI-00035
    name: 鈣思寶 - 鈣思寶大豆營鈣 Calci Plus CA+ SOYA CALCIUM (BONE) N 250毫升6包裝
    unit: 250ml
    unit-convertsion: price / 250 / 6 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H7509001_S_vtm2500601
    name: 維他奶 - 維他 鈣思寶 - 綠色 原味 250ml x 6 包
    unit: 250ml
    unit-convertsion: price / 250 / 6 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H7949001_S_DRKTNMILK004
    name: 維他 - 鈣思寶 - 高鈣大豆健康飲品 (原味) 1公升
    unit: 250ml
    unit-convertsion: price / 1000 * 250
    tags: 
      - 鈣思寶
  - source: hktvmall
    id: H7949001_S_DRKTNMILK003
    name: 維他 - 鈣思寶 - 無糖大豆高鈣健康飲品 1公升
    unit: 250ml
    unit-convertsion: price / 1000 * 250
    tags: 
      - 鈣思寶
