name: Daily Workflow

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 0 * * *' # At GMT 00:05

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout app repo
      uses: actions/checkout@v2
      with:
        path: app

    - name: Checkout data repo
      uses: actions/checkout@v2
      with:
        repository: badmikko/price-update
        token: ${{ secrets.COMMIT_TOKEN }}
        persist-credentials: false
        path: data
        
    - name: Install NodeJS
      uses: actions/setup-node@v1

    - name: Npm install
      run: npm install
      working-directory: ./app
      
    - name: Run app
      run: node ./price-download.js --dest ../data/Data
      working-directory: ./app

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY/MM/DD
    
    #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    - uses: EndBug/add-and-commit@v6 # You can change this to use a specific version
      with:
        author_name: ${{ secrets.COMMIT_NAME }}
        author_email: ${{ secrets.COMMIT_EMAIL }}
        cwd: './data'
        message: Daily refreshment on ${{ steps.current-time.outputs.formattedTime }}
        push: true
        signoff: true
        token: ${{ secrets.COMMIT_TOKEN }}
    